server:
  port: 9051

spring:
  devtools:
    livereload:
      enable: true
    restart:
      enable: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
